### ISSUE TITLE
git installing instructions require svn

### ISSUE THREAD

**Issue by pchtsp** [coin-or/Dip#100]
hello there!

I've just installed dip today. I have on small comment. In the [Unix installing instructions](https://projects.coin-or.org/Dip#DownloadandInstall), there are svn and git steps.

The git ones go like this:

    git clone --branch=stable/0.92 https://github.com/coin-or/Dip Dip-0.92
    cd Dip-0.92
    git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools/
    BuildTools/get.dependencies.sh fetch

First of all, the `BuildTools/get.dependencies.sh fetch` command requires svn, unless executed with the `--git` option. I guess it'd make sense to add the option in this command to make it proper git-compatible. So it would end up like: `BuildTools/get.dependencies.sh fetch --git`.

Secondly, even with the `--git` option activated, it still tries to use svn at some point. I got the error because I did not have it installed.
I got:

    BuildTools/get.dependencies.sh: line 271: svn: command not found

Of course, this is not critical. I just installed the `subversion` package for Ubuntu and that was it. I just though that maybe it would be nice to make the instructions a little more consistent. Or just take out the git ones altogether.

thanks!

Franco

**Comment by tkralphs** [comment]
Yes, I'm aware of this issue and it is not easy to fix right now, since there are some things we need that are not currently mirrored to Github. This will be fixed eventually. Thanks for opening the issue.
