### ISSUE TITLE
Setting a time limit with dippy

### ISSUE THREAD

**Issue by lucasemmoreira** [coin-or/Dip#101]
Hi there!

First of all, congratulations on the project. I've been playing for a couple of days and it is very nice!

I am using dippy to solve a vehicle routing problem and it would be nice if I could set a time limit for the solver via dippy (i.e. in my python code) since it is a hard problem to solve as the number of clients increases.
Where can I set this parameter or, if there is no parameter, could you give some hints on how I can make it happen?
I tried to check a portion of the codes inside the `dippy` folder, but I could not find any clues for this question.
I apologize if this question it is not supposed to be done here.

Best regards!

**Comment by tkralphs** [comment]
The second argument to the `solve` command is a dictionary of parameters to pass to `Dip`, so you set the time limit like this:
```
dippy.Solve(prob, {'TimeLimit': '100'})
```
Let me know if it works!
