### ISSUE TITLE
git installing instructions require svn

### ISSUE THREAD

**Issue by pchtsp** [coin-or/Dip#13]
hello there!

I've just installed dip today. I have on small comment. In the [Unix installing instructions](https://projects.coin-or.org/Dip#DownloadandInstall), there are svn and git steps.

The git ones go like this:

    git clone --branch=stable/0.92 https://github.com/coin-or/Dip Dip-0.92
    cd Dip-0.92
    git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools/
    BuildTools/get.dependencies.sh fetch

First of all, the `BuildTools/get.dependencies.sh fetch` command requires svn, unless executed with the `--git` option. I guess it'd make sense to add the option in this command to make it proper git-compatible. So it would end up like: `BuildTools/get.dependencies.sh fetch --git`.

Secondly, even with the `--git` option activated, it still tries to use svn at some point. I got the error because I did not have it installed.
I got:

    BuildTools/get.dependencies.sh: line 271: svn: command not found

Of course, this is not critical. I just installed the `subversion` package for Ubuntu and that was it. I just though that maybe it would be nice to make the instructions a little more consistent. Or just take out the git ones altogether.

thanks!

Franco

**Comment by tkralphs** [comment]
This is now fixed. The `Data` projects are now moved to Github. Also, there is a new script that uses `git` for everything by default. The script has been relocated to the [Optimization Suite](https://github.com/coin-or/COIN-OR-OptimizationSuite) project. To use, just do
```
git clone https://github.com/coin-or/COIN-OR-OptimizationSuite
cd COIN-OR-OptimizationSuite
./coin.install.sh --main-proj=Dip fetch build
```
It will use git by default. You also specify a particular version with something like 
```
./coin.install.sh --main-proj=Dip --main-proj-version=stable/0.92 fetch build
```
I'll update the documentation shortly. Let me know if you give it a try, as it's not been tested very widely.

**Comment by lucasemmoreira** [comment]
Greetings!

I have tried using my fork of Dip. I tried using the parameter for --main-proj-version with intuitive options such as 
`lucasemmoreira/Dip`
or 
`https://github.com/lucasemmoreira/Dip.git`
and a couple more of variations.
In all cases I got
```
Cloning into 'Dip'...
fatal: Remote branch lucasemmoreira/Dip.git not found in upstream origin
```
I am pretty sure I am missing some simple commands, but I am not sure what are those.

Thanks for your help!

**Comment by tkralphs** [comment]
Ah, OK, the script currently assumes that the main project lives in the `coin-or` organization. I didn't think about forks. It should not be difficult to support forks, but for now, I believe this should work.
```
git clone https://github.com/coin-or/COIN-OR-OptimizationSuite
cd COIN-OR-OptimizationSuite
git clone https://github.com/lucasemmoreira/Dip
./coin.install.sh --main-proj=Dip fetch build
```
I'll open the issue again until I get this resolved (although it is technically a separate issue).

**Comment by tkralphs** [comment]
Now you should be able to do
```
git clone https://github.com/coin-or/COIN-OR-OptimizationSuite
cd COIN-OR-OptimizationSuite
./coin.install.sh --main-proj=https://github.com/lucasemmoreira/Dip.git fetch build
```
Let me know how it goes.

**Comment by tkralphs** [comment]
By the way, I made another change to the `Dependencies` file in `Dip` (back to the original form, which I realized was actually needed) so make sure you merge changes before you try. This is all still a bit of a work in progress. Thanks for testing.

**Comment by lucasemmoreira** [comment]
No problem, it is a very nice project! 
It worked using my forked Dip.
Thank you very much for your help!
