### ISSUE TITLE
Where did BLAS and LAPACK deps go? 

### ISSUE THREAD

**Issue by spoorendonk** [coin-or/Dip#134]
Just a question.

They used in CLP (?), VOL (?), I guess. Not sure for what? 
And I figure there is a COIN specific implementation to cover the same ground since they are not included on windows by default because of the fortran compiler.

Were they not relevant for DIP?

**Comment by tkralphs** [comment]
Versions of Blas and Lapack that are better-performing than the ones we built from source are now easily available on every platform we support and found automagically by configure, so we decided not to support the ThirdParty projects going forward. On Linux and MacOS, they should be pre-installed. On Msys2, you can get them with pacman and there is MKL for Visual Studio. Our ThirdParty packages where doing more harm than good, to be honest.

**Comment by spoorendonk** [comment]
Cool. So if Blas and Lapack is installed then there is no need to pass flags to coinbrew? It will be detected automatically?

**Comment by tkralphs** [comment]
Yes, as long as they are installed in a standard location, which they generally should be. On Linux, there are many flavors of Blas and Lapack out there and for some, you may need some flags, but the search is pretty robust. If you just look at configure output, you will see whether they are found or not and be able to diagnose why they are not, if not, by looking at `config.log`.

**Comment by spoorendonk** [comment]
great
