### ISSUE TITLE
Allow use of SYMPHONY as MIP solver

### ISSUE THREAD

**Issue by svigerske** [coin-or/Dip#42]
Issue created by migration from Trac.

Original creator: @tkralphs

Original creation time: 2010-08-20 18:23:41

Hook up SYMPHONY through OSI so that it can be used as the subproblem solver.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2010-08-20 18:24:09

Changing priority from major to minor.

**Comment by svigerske** [comment]
Comment by @tkralphs created at 2010-08-20 18:24:09

Changing type from defect to enhancement.

**Comment by tkralphs** [comment]
This is done.
