### ISSUE TITLE
Error when installing Dip

### ISSUE THREAD

**Issue by svigerske** [coin-or/Dip#94]
Issue created by migration from Trac.

Original creator: blove

Original creation time: 2015-07-20 23:11:03

I'm trying to install dip and I get the following error when I run "make".  I'm attaching a text file with all the output.

CoinRational.cpp:56:18: error: use of undeclared identifier 'labs'; did you mean
      'fabs'?
   numerator_ += labs(intpart) * denominator_;
                 ^~~~
                 fabs
/usr/include/math.h:431:15: note: 'fabs' declared here
extern double fabs(double);
              ^
1 error generated.
make[3]: *** [CoinRational.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by svigerske** [comment]
Attachment [dip.txt](https://www.coin-or.org/issue-attachments/Dip/ticket94/dip.txt) by blove created at 2015-07-20 23:11:25

**Comment by tkralphs** [comment]
This is a problem with CoinUtils that has been fixed.
